### ISSUE TITLE
My OpenWebRX missing in listed on receiverbook.de

### ISSUE THREAD

**Issue by Doroshenko-T** [jketterl/receiverbook#1]
Dear Jakob,

My OpenWebRX server works steadily at http://kiev.extmail.info/

Unfortunately, he appeared https://www.receiverbook.de/ on list for a short time
and then disappeared.
Now I can neither add it nor delete it (in attachment).

Please, tell me what I have to do to make http://kiev.extmail.info/ appear on https://www.receiverbook.de/

Best regards,
T. Shilov
UR1229SWL

shilov@extmail.info

![kiev extmail info](https://user-images.githubusercontent.com/61428202/84547356-04cd5600-ad0c-11ea-9d3e-384d6e8974db.jpg)

**Comment by jketterl** [comment]
Hello,

the listing was public only during the period when I was implementing receiver verification.

Your receiver has been incorrectly detected as a websdr, not sure what went wrong there. It won't be possible to pass verification in that state.

I suggest to simply delete it and start over. If it is correctly detected this time (should be "openwebrx"), you should also be presented with the correct steps to take to get your listing online.

**Comment by Doroshenko-T** [comment]
Thanks you for the tip, but I could not find the “Delete” button.
Please tell me where is she located?

**Comment by jketterl** [comment]
Ah, I'm sorry, normally you'd navigate there using the "Name" column, but I just noticed that that's empty for you, as well. I just deployed a new version that should detect this, please check your receiver list again.

**Comment by Doroshenko-T** [comment]
Hooray! Now I again hit the your lists at https://www.receiverbook.de/
Great result, Jacob! Thank you very much for your help!

**Comment by Doroshenko-T** [comment]
I'm sorry, but the same problem occurred again :(
I have successfully upgraded version of OpenWebRX to 0.19.1.
Then I received a verification key
receiver_keys + = ["receiverbook-05d .............. f89"]

Added this key to the end of the file 'config_webrx.py'

Restarted the openwebrx service.
However, he does not work because an error occurred -

![Service openwebrx does not start](https://user-images.githubusercontent.com/61428202/84605912-e56c2f80-aea9-11ea-9633-0dc78b3f212e.png)

Therefore, I temporarily deleted this key so that the openwebrx service would work fine.

In the https://www.receiverbook.de/ lists, my receiver disappeared again.

What should I do now?

**Comment by jketterl** [comment]
There has been configuration changes with version 0.19.1, a new block for the `receiver_keys` has been introduced, you're missing the initialization of the variable that is in there. Please merge those changes into your configuration.

**Comment by Doroshenko-T** [comment]
I did not find a description of how to make a new block for 'receiver_keys'.
But somehow I managed to do this, add an empty line 'receiver_keys = []' above the line with the main key and then **my Receiver** 

**Radio Stations of Kiev, Ukraine
http://kiev.extmail.info**

again appeared in the lists on /https://www.receiverbook.de/

But a new problem arose: earlier my receiver occupied the honorable **7th** place in the list, right after 

**"DD5JFK development"
http://sdr2.justjakob.de**

now my receiver fell deep down to _15th_ place.

This is very it's a shame :(

Dear Jakob, I beg you restore fairness and return **my Receiver** to its previous **7th** place.
It is very important for me.

**Comment by jketterl** [comment]
There's no description. Look, it's very simple: There has been a new configuration for 0.19.1. When you updated, the package manager will have asked you if you want to install the new configuration or keep the current one. You more than likely answered that you'd like to keep your own, which is perfectly fine, but whenever you do so, it's up to you to merge the changes that the developer has done. In this case, I've added a new block, segment, paragraph, portion, piece... whatever you want to call it, really. Here, have a look at this, the green part is missing in your configuration now, and that's why it didn't work: https://github.com/jketterl/openwebrx/commit/8278ece803cddf53754d02fd0a546936bb8c0d50

I'm trying the configuration changes to be backwards compatible, but since this is a syntax issue, I cannot catch it in code and fix it for you.

As for the position: You are incorrectly assuming that the list is in some way ranked. That's just not the case, right now the listing is pretty much the same sequence that comes from the database. You've probably dropped down because you deleted and recreated your receiver listing.

Since there is no form of sorting, though, I don't have any influence over the results, and am therefore also not able to position any of the receivers, really. Sorry.

**Comment by Doroshenko-T** [comment]
I understood you. Thanks you, Jakob!

**Comment by Doroshenko-T** [comment]
Dear Jakob,

Previously, my receiver http://kiev.extmail.info  was at 7th place on the list at https://www.receiverbook.de/
Then for some reason he sank to 15th place and was there for a long time.

A few days ago, he was in 12th place, but today again got down to 14th place.

Why is this unwanted migration happening? Eventually in recent days I have not turned off my receiver.

Best regards,
T. Shilov
UR1229SWL

**Comment by jketterl** [comment]
As stated before, the list is not ranked in any way, and as such there is no point to speak of "places". This is not a competition, and there is no way for you (or me) to influence your position on the site.

I do not have any data to allow a meaningful ranking, and given the GDPR hell I'd have to go through to be able to collect any, it's not very likely this will change in the near future.

**Comment by Doroshenko-T** [comment]
Well', but if I stopping my OpenWebRX for a few hours or days to upgrade or repair equipment, my OpenWebRX place in the list will fall down again?

**Comment by jketterl** [comment]
You don't seem to understand. You are not in a place, so you cannot lose your place. Please stop interpreting the sequence that the receivers are listed in as any kind of ranking or placement.

At this time, I will not give out any guarantees or commitments of any kind that your receiver will be in the same spot on the site by tomorrow, no matter what. There is simply no deterministic or reproducible algorithm in place that would allow me to do so.

**Comment by Doroshenko-T** [comment]
Ok.
