### ISSUE TITLE
Site www.receiverbook.de incorrectly displays the number of Bands

### ISSUE THREAD

**Issue by Doroshenko-T** [jketterl/receiverbook#2]
Dear Jakob,

An unfortunate misunderstanding has occurred. You have improved your site and now it shows the radio bands of receivers.
However, he interprets them in his own way and incorrectly.
Because instead of the tuning frequencies of the receivers, it shows only amateur bands in meters.
But besides amateur bands there are also other non-standard, but also very interesting bands, however your site is not able to display them.

For example, I have 6 SDR receivers that accepts 6 different radio bands -

![My_6_Bands](https://user-images.githubusercontent.com/61428202/85347362-ff88bc00-b500-11ea-961c-cdfbb8b4865a.jpg)

however your site only shows 3 of them -

![Show_Only_3_Bands](https://user-images.githubusercontent.com/61428202/85347409-1f1fe480-b501-11ea-8247-99d0bcbf43ca.png)

This, unfortunately, is misleading to users, since they do not see the true number and frequency bands on your site.

Please, remake the site display so that it shows the real number of accepted bands.
For this can use, for example, the parameter "name" from "Profile" or "center_freq" from the main configuration file "config_webrx.py"

Thank you for understanding.

Best regards,
T. Shilov
UR1229SWL

**Comment by Abdula-2015** [comment]
jakob, I support this very important proposal. After all, the radio ether is much wider than amateur bands.
Users should be aware of the complete information about the OWR receivers and their tuning frequencies, not the trimmed information about them.

**Comment by jketterl** [comment]
OK guys... I'll ask for your proposal on what to do. The information provided by the receivers must be normalized, and no, I am not going to use the names of the profiles. Not after I have seen the spectrum of usefulness. What's your suggestion?

The bands you're seeing right now are provided by the bandplan that I knicked from the OpenWebRX project, simply because I don't have anything more comprehensive.

Keep in mind that this is about what a user would like to know, not what an operator would like to see on the site.

**Comment by UB6YDA** [comment]
Good evening.
First, thanks for your develop of OpenWebRX and thanks for the added feauters.

As I can see maybe can do both on site on websdr.org, instead of bands, user must see the borders of bands.
Example: my sdr receivers coverage 6 bands:
1. 2.9-3.9MHz
2. 6.2-7.2 Mhz
3. 27-28Mhz. 
etc.

So Let users see what boundaries my receivers cover.

Pictture for example
![bands](https://user-images.githubusercontent.com/8242601/85451348-71fda880-b5a2-11ea-87c0-584a282e08eb.jpg)


Sorry for my English, best regards US1GHQ -- 73!!!

**Comment by Doroshenko-T** [comment]
Oh yes! I agree with **Excalibur201010**: it’s better to immediately see the borders of the bands.
This is convenient and understandable and you do not need to go to every OpenWebRX site to see the real frequencies of each receivers.

Best regards,
T. Shilov
UR1229SWL

**Comment by Abdula-2015** [comment]
**Excalibur201010**: 

I agree with your option

![all_frequence](https://user-images.githubusercontent.com/12355404/85501274-b4000c00-b5ed-11ea-9455-3bf61a81cbc9.jpg)


It is the best, because the entire frequency environment is immediately visible.

**Comment by jketterl** [comment]
You may have noticed that I have taken down the markings now, mostly because of the fact there hasn't been a single user's voice heard. The consequence is: we obviously don't need that kind of display at all.

That frequency display of websdr.org is pretty cluttered, especially on bigger receivers, and it is hard to see much use at all. Expecting a user to crunch those numbers to find the receiver of choice is absolutely inacceptable, it takes way too much time and effort to do so. The human brain works better when offered visual stuff.

Even worse, the example you guys keep sending has overlapping ranges. Why would I confront the user with overlapping ranges? I'd be collapsing those, and you'd be going after me again for doing so.

I'm pissed off by the fact that you guys obviously are more interested in showcasing the most powerful receiver and not so much in what's most useful to the user. We are going to have a bad time.

**Comment by Doroshenko-T** [comment]
> The human brain works better when offered visual stuff.

I completely agree with you. But the table is actually faster perceived, however strange it may seem.


> there hasn't been a single user's voice heard.

> I'm pissed off by the fact that you guys obviously are more interested in showcasing the most powerful receiver and not so much in what's most useful to the user.

This is exactly what users will want - complete and understandable information, and not visual riddles that need to be guessed. They will really look for the most powerful receiver, because it will give them more opportunities to hear.

Okay, if you don’t want to show tables with range bounds, why don't you consider my initial sentence again?

**Comment by UB6YDA** [comment]
Thanks for your answer.
Primary idea so that the user knows what frequencies the receivers are working.
For example:
I know that the receivers (kiev.extmail.info) contain 6 bands, but showing only 3. 

Okay i have other idea's
1. Return showing bands (80m,40m etc), but if ranges is unknown showing their range frequencies
2. Reading names (or other things) from profiles of receivers.In this case, I think the information will be more reliable
3. Allow users to fill in the range bands in the user profile.

I repeat, I am for the correct display, since for me it is very important when setting up the transceiver and looking for receivers.

Thanks and best regards US1GHQ - 73!

**Comment by jketterl** [comment]
> This is exactly what users will want - complete and understandable information, and not visual riddles that need to be guessed. They will really look for the most powerful receiver, because it will give them more opportunities to hear.

OK first of all, riddle me this: what is the 147MHz and the 423MHz ranges for? They seem to be commercial / private frequencies that shouldn't be of public interest, tell me why I should advertise those ranges at all?

The 446 covers the PMR band... yet nobody has come up with the simple suggestion of adding that to the band plan?

**Comment by Doroshenko-T** [comment]
147-148 MHz,, 172 MHz, 423 MHz, etc. are of most interest because the police and private security agencies and other city services work there. 
It is there that curious and importment events take place that cause the greatest public interest among radio listeners, because they want to quickly find out what really happens in the city, and not read about it in a distorted form from journalists on the Internet on the second day.
Listeners should be given complete freedom of choice of frequencies and inform them of this, and not limit their freedom.

Best regards,
T. Shilov
UR1229SWL

**Comment by Abdula-2015** [comment]
Reputable Jakob,

You are a successful developer of excellent program OpenWebRX.
But you do not have to worry about what frequencies are used by site administrators with OpenWebRX, becouse this is only their prerogative.
Administrators should take into account only the opinions of own listeners, and give them frequencies that they like best, no matter how strange they seem.

I am an ordinary listener of the radio ether, I do not have OpenWebRX, but I love to listen to him.

**Comment by jketterl** [comment]
> 147-148 MHz,, 172 MHz, 423 MHz, etc. are of most interest because the police and private security agencies and other city services work there.

> Listeners should be given complete freedom of choice of frequencies and inform them of this, and not limit their freedom.

Well let me hereby officially inform you that under my legislation it is illegal to listen to or share transmissions of services on these frequencies. https://de.wikipedia.org/wiki/Telekommunikationsgesetz_(Deutschland) paragraph "Abhören von Nachrichten".

I don't intend to interfere with what frequencies you make available on your receivers; however, I keep my reservations about what information I will represent on the directory.

**Comment by linkfanel** [comment]
Maybe a visual representation of the available spectrum could be generated: a spectrum bar with graduations marking frequencies and wavelengths, where available bands are filled with a color, and the rest left blank or transparent. This way, overlapping bands and technical hardware specifics are naturally collapsed, and the user can see at a quick glance how much spectrum is available, and where.

A color gradient or other specific color cues could also be used so users can easily recognize familiar bands.

This is also about more than shortwave - I see some setups go pretty high into UHF, so the length of the spectrum bar could be dynamic and/or use a logarithmic scale to accomodate that.

**Comment by Abdula-2015** [comment]
> Well let me hereby officially inform you that under my legislation it is illegal to listen to or share transmissions of services on these frequencies. https://de.wikipedia.org/wiki/Telekommunikationsgesetz_(Deutschland) paragraph "Abhören von Nachrichten".

O, yes, this is a great law. If you executed it completely, then  need to prohibit OpenWebRX, WebSDR, KiwiSDR, etc., because they broadcast amateur radio conversations without permissions of radio users.

**Comment by jketterl** [comment]
> O, yes, this is a great law. If you executed it completely, then need to prohibit OpenWebRX, WebSDR, KiwiSDR, etc., because they broadcast amateur radio conversations without permissions of radio users.

I don't really intend to discuss the effectiveness a law will have to prevent people from eavesdropping. However, it does not apply to all radio services. Amateur radio does not enjoy this protection, nor do broadcast bands, CB radio, or PMR. There's probably a whole list of others as well, but I don't have a comprehensive collection, as stated earlier.

**Comment by Tamila-2017** [comment]
Hi,

> There is already an ongoing discussion in #2 that has led to the removal of the band display since some users felt their efforts were underrepresented by it. So far, this discussion has failed to produce a meaningful alternative (and that may have to do with the fact that I don't intend to replicate websdr.org). Please use the existing ticket to discuss the issue.

I understand you, Jakob.  

And since no one offers new creative ideas on this topic, please turn on your band display.
This will be much better than the complete lack of information about ranges on your site.
I hope for your loyal understanding of my request, which will be useful to everyone.

All the best!

**Comment by Tamila-2017** [comment]
Hi,

Jakob, why are you ignoring my request? Why are you silent?
I am very surprised at such indifference to a useful suggestion.

**Comment by jketterl** [comment]
What makes you think that I'm ignoring your request? Do you always expect others to jump into action immediately?

**Comment by Tamila-2017** [comment]
Hi,

What are you, I do not believe that you should immediately do something!
But for 10 days you did not respond to my request, and therefore I decided that you did not want to do anything for her.

**Comment by jketterl** [comment]
Wow. Just because I don't acknowledge every suggestion personally does not mean I don't read them. I'm not actively working on features for receiverbook at the moment, mainly because OpenWebRX takes up a lot of time already, but also because this little project turned out to be no fun.

**Comment by Tamila-2017** [comment]
> Just because I don't acknowledge every suggestion personally does not mean I don't read them.

It is wonderful :)

> but also because this small project turned out to be uninteresting.

But to us, radio listeners, it is very interesting! It very makes it easier to find interesting OpenWebRX.

Jakob, please just return your old "band display", and that will be enough for now.
