### ISSUE TITLE
Add bands to the list

### ISSUE THREAD

**Issue by Tamila-2017** [jketterl/receiverbook#5]
Hi, 

Please add bands to the list receiverbook.de
They are sorely missed.
Better like here: websdr.org
Very convenient to use.

**Comment by jketterl** [comment]
There is already an ongoing discussion in https://github.com/jketterl/receiverbook/issues/2 that has led to the removal of the band display since some users felt their efforts were underrepresented by it. So far, this discussion has failed to produce a meaningful alternative (and that may have to do with the fact that I don't intend to replicate websdr.org).

Please use the existing ticket to discuss the issue.
